apiVersion: v2
name: stack
description: A unified Helm chart for deploying Rulebricks and its dependencies (Kafka, Supabase, Traefik, etc.)
type: application
version: 0.1.0
appVersion: "0.1.0"
icon: https://d1zic6dm9txw4h.cloudfront.net/rulebricks-docs-assets/static/images/application/logo.png
home: https://rulebricks.com
sources:
  - https://github.com/rulebricks/charts
maintainers:
  - name: Rulebricks
    email: support@rulebricks.com
    url: https://rulebricks.com
keywords:
  - rulebricks
  - rules-engine
  - business-rules
  - decision-engine
  - enterprise
dependencies:
  - name: rulebricks
    version: 0.1.0
    repository: file://charts/rulebricks
  - name: common
    version: 2.31.4
    repository: file://charts/common
  - name: kafka
    version: 32.4.4
    repository: file://charts/kafka
    condition: kafka.enabled
  - name: supabase
    version: 0.1.3
    repository: file://charts/supabase
    condition: supabase.enabled
  - name: kube-prometheus-stack
    version: 67.6.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.enabled
  - name: traefik
    version: 33.1.0
    repository: https://helm.traefik.io/traefik
    condition: traefik.enabled
  - name: keda
    version: 2.16.0
    repository: https://kedacore.github.io/charts
    condition: keda.enabled
  - name: cert-manager
    version: v1.16.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: vector
    version: 0.40.0
    repository: https://helm.vector.dev
    condition: vector.enabled
  - name: external-dns
    version: 1.14.5
    repository: https://kubernetes-sigs.github.io/external-dns/
    condition: external-dns.enabled
