# An example minimum configuration for a Rulebricks cluster
# Storage is required - customize the storage class in the values.yaml file accordingly

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: rulebricks-cluster
  region: us-east-1
  version: "1.33"

managedNodeGroups:
  - name: standard-nodes
    amiFamily: AmazonLinux2023
    instanceType: m7i.xlarge
    minSize: 3 # Minimum CPU/memory requirements
    maxSize: 5
    desiredCapacity: 3
    volumeSize: 50
    volumeType: gp3
    iam:
      withAddonPolicies:
        ebs: true
        albIngress: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: aws-ebs-csi-driver # Required for PVCs
