#!/usr/bin/env bash
set -euo pipefail
#
# render-digests.sh
#
# Read the resolved image digests and write them back into the repo, in two
# places:
#   1. chart values.yaml -> .global.imageDigests  (consumed by the image helper)
#   2. images/manifest.yaml -> each entry's .digest  (audit trail)
#
# The digests come from images/digests.json. If digests.json does not yet exist
# (e.g. the CI `pin` job has just downloaded per-image <name>.digest artifacts but
# not assembled them), this script first builds images/digests.json from the
# fragments found under ${OUT_DIR} (recursively — download-artifact@v4 nests each
# under its own directory).
#
# Idempotent: re-running with the same digests produces no further change. It does
# NOT reorder or destroy unrelated content — yq edits in place and only touches
# the targeted keys.
#
# NOTE: values.yaml is owned by another worker and is not present in this branch
# while these scripts are authored; this script is written to run in CI against
# the real chart, and no-ops gracefully (with a warning) if values.yaml is absent.
#
# NOTE: the CLI repo's src/lib/versions.ts IMAGE_DIGESTS const is regenerated by a
# SEPARATE step in the CLI repo that consumes this same images/digests.json. That
# regeneration is OUT OF SCOPE for this (helm) repo — see the emitted note below.
#
# Env:
#   DIGESTS_JSON   digests source/output (default: <repo>/images/digests.json)
#   MANIFEST       manifest path (default: <repo>/images/manifest.yaml)
#   VALUES_FILE    chart values (default: <repo>/values.yaml)
#   OUT_DIR        where <name>.digest fragments live, if assembling (default: /tmp)
#
# Requires: yq, jq.

_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/images/common.sh
. "${_dir}/common.sh"

DIGESTS_JSON="${DIGESTS_JSON:-${REPO_ROOT}/images/digests.json}"
VALUES_FILE="${VALUES_FILE:-${REPO_ROOT}/values.yaml}"

usage() {
  cat >&2 <<EOF
usage: ${0##*/}

Write image digests from ${DIGESTS_JSON} back into:
  - ${VALUES_FILE} (.global.imageDigests)
  - ${MANIFEST} (per-entry .digest)
If ${DIGESTS_JSON} is absent, it is first assembled from \${OUT_DIR:-/tmp}/*.digest.
EOF
}

# assemble_digests_json — build images/digests.json from <name>.digest fragments
# found anywhere under OUT_DIR (download-artifact@v4 nests each in its own dir).
assemble_digests_json() {
  echo "==> ${DIGESTS_JSON} not found; assembling from fragments under ${OUT_DIR}"
  local found=()
  while IFS= read -r frag; do
    found+=("${frag}")
  done < <(find "${OUT_DIR}" -type f -name '*.digest' 2>/dev/null | sort)

  [ "${#found[@]}" -gt 0 ] || die "no <name>.digest fragments found under ${OUT_DIR}"

  # Build a {name,digest} JSON stream then reduce to a sorted-key object. Names
  # may contain hyphens, so they are passed as jq DATA (--arg), never identifiers.
  local stream="" frag name digest
  for frag in "${found[@]}"; do
    name="$(basename "${frag}" .digest)"
    digest="$(cat "${frag}")"
    [ -n "${digest}" ] || die "empty digest fragment: ${frag}"
    case "${digest}" in
      sha256:*) : ;;
      *) die "digest fragment ${frag} is not a sha256 ref: ${digest}" ;;
    esac
    stream+="$(jq -cn --arg n "${name}" --arg d "${digest}" '{name:$n,digest:$d}')"$'\n'
  done

  mkdir -p "$(dirname "${DIGESTS_JSON}")"
  printf '%s' "${stream}" \
    | jq -s --sort-keys 'reduce .[] as $e ({}; .[$e.name] = $e.digest)' \
    > "${DIGESTS_JSON}"
  echo "wrote ${DIGESTS_JSON}"
}

# patch_values — set .global.imageDigests in values.yaml from digests.json.
patch_values() {
  if [ ! -f "${VALUES_FILE}" ]; then
    echo "warning: ${VALUES_FILE} not found; skipping values.yaml digest patch" >&2
    echo "         (expected in CI; another worker owns values.yaml)" >&2
    return 0
  fi
  echo "==> patching ${VALUES_FILE} .global.imageDigests"
  # load() merges the JSON object verbatim under the key. yq edits in place and
  # leaves all other keys/comments/ordering untouched. Idempotent.
  DIGESTS_JSON="${DIGESTS_JSON}" yq -i \
    '.global.imageDigests = load(env(DIGESTS_JSON))' \
    "${VALUES_FILE}"
}

# patch_manifest — write each digest back into its manifest entry's .digest field.
patch_manifest() {
  echo "==> patching ${MANIFEST} per-entry .digest fields"
  local name digest
  while IFS= read -r name; do
    [ -n "${name}" ] || continue
    digest="$(jq -r --arg n "${name}" '.[$n] // ""' "${DIGESTS_JSON}")"
    if [ -z "${digest}" ] || [ "${digest}" = "null" ]; then
      echo "warning: no digest for manifest entry '${name}' in ${DIGESTS_JSON}; leaving as-is" >&2
      continue
    fi
    # Update only the matching entry's .digest; everything else is preserved.
    NAME="${name}" DIGEST="${digest}" yq -i \
      '(.images[] | select(.name == env(NAME)) | .digest) = env(DIGEST)' \
      "${MANIFEST}"
  done < <(manifest_names)
}

main() {
  if [ "$#" -gt 0 ]; then
    case "$1" in
      -h|--help) usage; exit 0 ;;
      *) usage; die "unexpected argument: $1" ;;
    esac
  fi

  require_cmd yq
  require_cmd jq
  require_manifest

  [ -f "${DIGESTS_JSON}" ] || assemble_digests_json
  [ -f "${DIGESTS_JSON}" ] || die "digests source missing and could not be assembled: ${DIGESTS_JSON}"

  patch_values
  patch_manifest

  cat <<'EOF'

note: the CLI repo's src/lib/versions.ts IMAGE_DIGESTS const is regenerated by a
      SEPARATE step in the CLI repo that consumes this same images/digests.json.
      That codegen is out of scope for the helm repo and is NOT performed here.
EOF
  echo "done."
}

main "$@"
