{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled .Values.hps.enabled .Values.hps.workers.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rulebricks-chart.hps-worker.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rulebricks-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: hps-worker
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: hps-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      path: {{ .Values.metrics.worker.path | default "/metrics" | quote }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
{{- end }}
