{{- if and .Values.backup .Values.backup.enabled }}
{{- $storageAnnotations := include "rulebricks.storage.serviceAccountAnnotations" . | trim }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rulebricks.backup.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "rulebricks.backup.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: db-backup
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.global.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or $storageAnnotations .Values.global.annotations }}
  annotations:
    {{- if $storageAnnotations }}
    {{- $storageAnnotations | nindent 4 }}
    {{- end }}
    {{- with .Values.global.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
