{{- if and (index .Values "cert-manager" "enabled") .Values.rulebricks.app.tlsEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Release.Name }}-tls-secret
  issuerRef:
    name: {{ .Release.Name }}-letsencrypt
    kind: ClusterIssuer
  dnsNames:
  {{- range .Values.rulebricks.ingress.hosts }}
    - {{ .host }}
  {{- end }}
  # Optional: Add common name
  commonName: {{ (index .Values.rulebricks.ingress.hosts 0).host }}
{{- end }}

