{{- if and (index .Values "cert-manager" "enabled") .Values.global.tlsEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Release.Name }}-tls-secret
  issuerRef:
    name: {{ .Release.Name }}-letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.global.domain }}
  commonName: {{ .Values.global.domain }}
{{- end }}
