{{- if .Values.clickhouse.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-clickhouse-credentials" .Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: clickhouse
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  admin-password: {{ include "common.secrets.passwords.manage" (dict "secret" (printf "%s-clickhouse-credentials" .Release.Name) "key" "admin-password" "length" 32 "providedValues" (list "clickhouse.auth.password") "context" $) }}
{{- end }}
