{{- if .Values.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clickstack.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "clickstack.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "clickstack.fullname" . }}
  labels:
    {{- include "clickstack.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["nodes/stats", "nodes/proxy"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "clickstack.fullname" . }}
  labels:
    {{- include "clickstack.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "clickstack.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "clickstack.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
